(setq gud-gdb-command-name "gdb --annotate=3 bin/tester ")
(command-execute 'gdb)
(setq gdb-many-windows t)
(setq compile-command "cd .. && make debug")
(setq column-number-mode t)
(setq auto-fill-mode 1)
(setq-default fill-column 80)
(setq-default indent-tabs-mode t) 
(global-set-key [f12] 'compile)
(print "*** Debugging eblearn_tester with emacs and gdb.***")
(print "type \"r -nocolor\" to start debugging eblearn_tester")
(setq initial-frame-alist (append '((tool-bar-lines . 1)) initial-frame-alist))
